# Taskboard Configuration Example
# Copy this file to config.yaml and adjust values as needed
# All values can be overridden with environment variables using TASKBOARD_ prefix
# Example: TASKBOARD_REDIS_HOST=redis.example.com

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  username: ""
  use_tls: false

  # TLS Configuration (only used if use_tls is true)
  tls:
    # Path to client certificate file
    cert_file: ""
    # Path to client key file
    key_file: ""
    # Path to CA certificate file
    ca_file: ""
    # Skip TLS certificate verification (not recommended for production)
    insecure_skip_verify: false

api:
  port: 1337
